version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: "@angular-builders/custom-webpack"
    versions:
    - 11.0.0
    - 11.1.0
